### ISSUE TITLE
Bot crashes when you send an uncompressed image

### ISSUE THREAD

**Issue by icecube45** [Liryna/FacebookBot#5]
I'll have to investigate this in more detail when I have some more time, but sending compressed images still works as it should.

**Comment by Liryna** [comment]
I have never tested it to tell the truth :+1:

**Comment by Schmavery** [comment]
We've been having a number of issues with image upload using the facebook-chat-api.  If this issue still happens using version 1.0.6 of the api, I would really appreciate if you could open an issue on our [repo](https://github.com/Schmavery/facebook-chat-api) and upload an example file that fails on send.
